# Generated by Django 3.2.7 on 2021-10-01 16:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bid_start_date', models.DateField(default=datetime.date.today)),
                ('bid_close_date', models.DateField(default=datetime.date.today)),
                ('base_price', models.FloatField(default=0.0)),
                ('is_Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('adhr_no', models.IntegerField(primary_key=True, serialize=False)),
                ('farm_exp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('adhr_no', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('crop_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=100, null=True)),
                ('season', models.CharField(choices=[('Rabi', 'Rabi'), ('Kharif', 'Kharif')], max_length=15)),
                ('qty_grown', models.FloatField(default=0.0)),
                ('in_stock', models.BooleanField(default=True)),
                ('crop_type', models.CharField(max_length=30)),
                ('qty_predicted', models.FloatField(default=0.0)),
                ('bid_for_crop', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bidding.bid')),
                ('grown_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='BidEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.FloatField(default=0.0)),
                ('bid_time', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.bid')),
                ('merchant_bidding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.merchant')),
            ],
        ),
    ]
